[package]
name = "whirlpool"
version = "0.1.0"
edition = "2021"
authors = ["boris.lok <boris.lok.tw@outlook.com>"]

[dependencies]
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
anyhow = "1.0.70"
rand = "0.8.5"